# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'

# Define services
services:
  # App backend service
  car-api:
    # Configuration for building the docker image for the backend service
    build:
      context: car-api # Use an image built from the specified dockerfile in the `car-api` directory.
      dockerfile: Dockerfile
    ports:
      - "9595:9595" # Forward the exposed port 9595 on the container to port 9595 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/car-market?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: market
      SPRING_DATASOURCE_PASSWORD: market 
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service 
  car-ui:
    build:
      context: car-ui # Use an image built from the specified dockerfile in the `car-ui` directory.
      dockerfile: Dockerfile
    ports:
      - "8081:80" # Map the exposed port 80 on the container to port 8081 on the host machine
    restart: always
    depends_on:
      - car-api
    networks:
      - frontend  

  # Database Service (Mysql)
  db:
    image: mysql:8.0
    ports:
      - "3307:3307"
    restart: always
    environment:
      MYSQL_DATABASE: car-market
      MYSQL_USER: market
      MYSQL_PASSWORD: market
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend  
  
# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: